version: '3'
services:
  ksproject_golang:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ksproject_golang
    restart: always
    ports:
      - 3001:8081
    env_file:
      - ./.env